-- Publish 130 original prompts for the pinned NeetCode 150 catalog.
-- Apply with the matching application registry; historical interview snapshots
-- and the two existing version-2 corrections remain untouched.
do $$
declare
  slugs text[] := array[
    '3sum',
    'add-two-numbers',
    'alien-dictionary',
    'balanced-binary-tree',
    'best-time-to-buy-and-sell-stock-with-cooldown',
    'binary-tree-level-order-traversal',
    'binary-tree-maximum-path-sum',
    'binary-tree-right-side-view',
    'burst-balloons',
    'car-fleet',
    'cheapest-flights-within-k-stops',
    'clone-graph',
    'coin-change',
    'coin-change-ii',
    'combination-sum',
    'combination-sum-ii',
    'construct-binary-tree-from-preorder-and-inorder-traversal',
    'container-with-most-water',
    'copy-list-with-random-pointer',
    'count-good-nodes-in-binary-tree',
    'counting-bits',
    'course-schedule',
    'course-schedule-ii',
    'daily-temperatures',
    'decode-ways',
    'design-add-and-search-words-data-structure',
    'design-twitter',
    'detect-squares',
    'diameter-of-binary-tree',
    'distinct-subsequences',
    'edit-distance',
    'encode-and-decode-strings',
    'evaluate-reverse-polish-notation',
    'find-median-from-data-stream',
    'find-minimum-in-rotated-sorted-array',
    'find-the-duplicate-number',
    'gas-station',
    'generate-parentheses',
    'graph-valid-tree',
    'group-anagrams',
    'hand-of-straights',
    'happy-number',
    'house-robber',
    'house-robber-ii',
    'interleaving-string',
    'invert-binary-tree',
    'jump-game',
    'jump-game-ii',
    'k-closest-points-to-origin',
    'koko-eating-bananas',
    'kth-largest-element-in-an-array',
    'kth-smallest-element-in-a-bst',
    'largest-rectangle-in-histogram',
    'last-stone-weight',
    'letter-combinations-of-a-phone-number',
    'linked-list-cycle',
    'longest-common-subsequence',
    'longest-consecutive-sequence',
    'longest-increasing-path-in-a-matrix',
    'longest-increasing-subsequence',
    'longest-palindromic-substring',
    'longest-repeating-character-replacement',
    'longest-substring-without-repeating-characters',
    'lowest-common-ancestor-of-a-binary-search-tree',
    'lru-cache',
    'max-area-of-island',
    'maximum-depth-of-binary-tree',
    'maximum-product-subarray',
    'meeting-rooms',
    'meeting-rooms-ii',
    'merge-intervals',
    'merge-triplets-to-form-target-triplet',
    'merge-two-sorted-lists',
    'min-cost-climbing-stairs',
    'min-cost-to-connect-all-points',
    'min-stack',
    'minimum-interval-to-include-each-query',
    'minimum-window-substring',
    'missing-number',
    'multiply-strings',
    'n-queens',
    'non-overlapping-intervals',
    'number-of-1-bits',
    'number-of-connected-components-in-an-undirected-graph',
    'pacific-atlantic-water-flow',
    'palindrome-partitioning',
    'palindromic-substrings',
    'partition-equal-subset-sum',
    'partition-labels',
    'permutation-in-string',
    'permutations',
    'plus-one',
    'powx-n',
    'product-of-array-except-self',
    'reconstruct-itinerary',
    'redundant-connection',
    'regular-expression-matching',
    'remove-nth-node-from-end-of-list',
    'reorder-list',
    'reverse-bits',
    'reverse-integer',
    'reverse-nodes-in-k-group',
    'rotting-oranges',
    'same-tree',
    'search-a-2d-matrix',
    'search-in-rotated-sorted-array',
    'set-matrix-zeroes',
    'sliding-window-maximum',
    'spiral-matrix',
    'subsets-ii',
    'subtree-of-another-tree',
    'sum-of-two-integers',
    'surrounded-regions',
    'swim-in-rising-water',
    'target-sum',
    'task-scheduler',
    'time-based-key-value-store',
    'top-k-frequent-elements',
    'trapping-rain-water',
    'two-sum',
    'two-sum-ii-input-array-is-sorted',
    'valid-anagram',
    'valid-parenthesis-string',
    'valid-sudoku',
    'validate-binary-search-tree',
    'walls-and-gates',
    'word-break',
    'word-ladder',
    'word-search',
    'word-search-ii'
  ];
  matched integer;
begin
  select count(*) into matched from public.problems
    where source = 'leetcode' and slug = any(slugs);
  if matched <> 130 then
    raise exception 'NeetCode expansion requires exactly 130 matching catalog entries, found %', matched;
  end if;
  if exists (select 1 from public.problems
    where source = 'leetcode' and slug = any(slugs) and interview_ready
      and (interview_content_version <> 1 or interview_content_provenance <> 'first_party')) then
    raise exception 'Unexpected published content version in NeetCode expansion';
  end if;
  update public.problems
    set interview_ready = true,
        interview_content_version = 1,
        interview_content_provenance = 'first_party'
    where source = 'leetcode' and slug = any(slugs) and not interview_ready;
end;
$$;
